name: goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --timeout 2m
